### ISSUE TITLE
Great work，Some issues

### ISSUE THREAD

**Issue by ElliottZhen** [OrigamiSL/OTETrack#1]
Great job~
I would like to ask a couple of questions:
1. can you please tell me how the FPS is tested in the UAV123 dataset in the article, it should not be the proflie_model file.
2. about the patchembed of overlappedViT, can I understand it as halving the patchembed step in the original ViT,to get a feature map of 31*31 size, and then splitting it in adjacent intervals to get two feature maps?
Thank you very much for your contribution to the community.
Looking forward to your reply!
@OrigamiSL

**Comment by OrigamiSL** [comment]
Thanks for your concerns.
Q1: The file for speed evaluation is not included in this work. Sorry for the inconvenience. However, it is quite easy to test it by yourself with our code. Note that only the computation in the network accounts for the evaluation of FPS and the batch size is one during the inference to comply with the real-world practice (The FPSs of other models are obtained by the same way so that you may find that our FPS results of other baselines are normally faster than the ones given in their raw papers.).
Q2: Definitely. I admit that this operation is sort of wasting computing resources, however it is convenient to be implemented.

**Comment by OrigamiSL** [comment]
It can. However, you may merely use its partial functions or need to use it with proper modifications. It may be not that convenient. The confidence of an arbitrary tracker can be used to determine whether to use SES or HES for predicting the center of Ladder-shaped Hanning window. If the tracker you adopt does not have an output for confidence, then you can consistently use SES for prediction. Nevertheless, in any case, the Ladder-shaped Hanning window and the prediction, no matter it is based on SES, HES or others, for obtaining the window center are always available.
Take OSTrack as an example, its head is CNN-based with multiple output candidates and the confidence score. I'm sure that they can be fully combined with our methods. Note that this code is implemented on the basis of those of OSTrack and ARTrack. Therefore, I think it won't take you much time for modifications.

**Comment by OrigamiSL** [comment]
That means that the preprocessing procedures, e.g., loading the images, cropping the images, and some postprocessing procedures, e.g., recovering the images, saving the images, do not account.
We use the time module (import time) to compute the total inference time of UAV dataset, then take the average to obtain the FPS.

**Comment by OrigamiSL** [comment]
That means that the preprocessing procedures, e.g., loading the images, cropping the images, and some postprocessing procedures, e.g., recovering the images, saving the images, do not account.
We use the time module (import time) to compute the total inference time of UAV dataset, then take the average to obtain the FPS.
